### ISSUE TITLE
course missing: 3-091-introduction-to-solid-state-chemistry-fall-2018

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-data-parser#170]
for some reason the course at s3://ocw-content-storage/PROD/3/3.091/Fall_2018/3-091-introduction-to-solid-state-chemistry-fall-2018/0 will not parse. 

It seem like the file `1.json` does not contain the necessary metdata for ocw-data-parser to recognize it as a course. 

We need to find a way to reconstruct this course's raw JSON, or figure out how to fix the export from Plone.

**Comment by abeglova** [comment]
I looked into the course data and it looks like 1.json at s3://ocw-content-storage/PROD/3/3.091/Fall_2018/3-091-introduction-to-solid-state-chemistry-fall-2018/0 contains the data that should be in 2.json. This is the the data with     "_classname": "CourseHomeSection" which is the plone output for the course home page. Unfortunately the data that should be in 1.json, which should have    "_classname": "Course",  is completely missing. It's definitely not possible to parse the course without this data because it contains all the course level information such as the title, course number and instructors.

**Comment by abeglova** [comment]
This is pretty weird because https://ocw.mit.edu/courses/materials-science-and-engineering/3-091-introduction-to-solid-state-chemistry-fall-2018/ looks totally normal

**Comment by abeglova** [comment]
So I parsed the files in ocw-content-storage and looks like this is the only course with this issue

It might be faster to recreate it than figure out what's wrong with the Plone export

**Comment by abeglova** [comment]
Since the course contains more than 900 pages/resources, I will create a new 1.json file with the minimum course data to make the course parsable and import the course into ocw-studio that way

The ocw team will still need to make a few edits to the course level data but the rest of the course data will be imported for them

**Comment by abeglova** [comment]
I imported the course into both RC and prod
