### ISSUE TITLE
add HFH parsing capability

### ISSUE THREAD

**Issue by kyfantaz** [mitodl/ocw-data-parser#4]
example: https://ocw.mit.edu/high-school/chemistry/chemistry-lab-boot-camp/
HFH_chemistry_2018-01-16-06-47-11

**Comment by pdpinch** [comment]
This title keeps confusing me, because MIT Open Learning has a separate product called "bootcamps" 

From an OCW perspective, this is actually a "high-school" or "HFH" course. I'm not sure, but I presume the same parser could handle all HFH courses. 

(I'd change the title of the issue, but I don't have permission)

**Comment by pdpinch** [comment]
We decided to handle these courses manaully
